trigger:
- main
- develop

name: $(Build.SourceBranchName)-$(Date:ddMMyy)-$(Rev:rr)-$(Build.DefinitionName)

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    ls -ltr
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
