trigger:
- main
- develop

name: $(Build.SourceBranchName)-$(Date:ddMMyy)-$(Rev:rr)-$(Build.DefinitionName)

pool:
  vmImage: ubuntu-latest

variables:
- group: DEV_GROUP

jobs:
- job: waitForValidation
  displayName: Wait for external validation
  pool: server
  timeoutInMinutes: $(jobTimeoutInMinutes)
  steps:
  - task: ManualValidation@0
    timeoutInMinutes: 20
    inputs:
      notifyUsers: |
        test@test.com
        example@example.com
      instructions: 'Please validate the build configuration and resume'
      onTimeout: 'resume'
