trigger:
- main
- develop

name: $(Build.SourceBranchName)-$(Date:ddMMyy)-$(Rev:rr)-$(Build.DefinitionName)

pool:
  vmImage: ubuntu-latest

jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 1 # job times out in 3 days
    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            # Write your commands here
            
            echo 'Hello world'