name: Build Operation Report Tool
on: 
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths-ignore:
            - '.github/workflows/**'
jobs:
    first-play:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Hello world
              run:  echo "hello"
            - name: List file before checkout
              run:  ls -lrt; echo "${{ secrets.HELLO }} and ${{ vars.HELLO_VAR }}"
            - name: Code Checkout
              uses: actions/checkout@v2
            - name: List file after checkout
              run:  ls -lrt
