name: Build Operation Report Tool
on: 
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths-ignore:
            - '.github/workflows/**'
jobs:
    first-play:
        runs-on: ubuntu-latest
        steps:
            - name: Hello world
              run:  echo "hello"
